---
- name: Enable only compute and metadata APIs.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: DEFAULT
    option:  enabled_apis
    value:   osapi_compute,metadata

- name: Configure DB access.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: '{{ item.section }}'
    option:  connection
    value:   '{{ item.value }}'
  with_items:
    - section: api_database
      value:   'mysql+pymysql://nova:{{ mysql_password }}@{{ mysql_host }}/nova_api'
    - section: database
      value:   'mysql+pymysql://nova:{{ mysql_password }}@{{ mysql_host }}/nova'

- name: Use RabbitMQ.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: DEFAULT
    option:  rpc_backend
    value:   rabbit

- name: Configure RabbitMQ access.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: oslo_messaging_rabbit
    option:  '{{ item.option }}'
    value:   '{{ item.value }}'
  with_items:
    - option: rabbit_host
      value:  '{{ rabbitmq_host }}'
    - option: rabbit_userid
      value:  '{{ rabbitmq_user }}'
    - option: rabbit_password
      value:  '{{ rabbitmq_password }}'

- name: Use Keystone.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: DEFAULT
    option:  auth_strategy
    value:   keystone

- name: Configure Keystone access.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: keystone_authtoken
    option:  '{{ item.option }}'
    value:   '{{ item.value }}'
  with_items:
    - option: auth_uri
      value:  'http://{{ keystone_host }}:5000'
    - option: auth_url
      value:  'http://{{ keystone_host }}:35357'
    - option: memcached_servers
      value:  '{{ keystone_host }}:11211'
    - option: auth_type
      value:  password
    - option: project_domain_name
      value:  default
    - option: user_domain_name
      value:  default
    - option: project_name
      value:  service
    - option: username
      value:  nova
    - option: password
      value:  '{{ keystone_password }}'

- name: Configure management interface IP.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: DEFAULT
    option:  my_ip
    value:   '{{ ip_address }}'

- name: Configure networking.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: DEFAULT
    option:  '{{ item.option }}'
    value:   '{{ item.value }}'
  with_items:
    - option: use_neutron
      value:  true
    - option: firewall_driver
      value:  nova.virt.firewall.NoopFirewallDriver

- name: Configure VNC proxy.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: vnc
    option:  '{{ item }}'
    value:   '{{ ip_address }}'
  with_items:
    - vncserver_listen
    - vncserver_proxyclient_address

- name: Configure Glance access.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: glance
    option:  api_servers
    value:   'http://{{ glance_host }}:9292'

- name: Configure lock path.
  ini_file:
    dest:    /etc/nova/nova.conf
    section: oslo_concurrency
    option:  lock_path
    value:   /var/lib/nova/tmp
