---
- name: Configure Nova services.
  service:
    name:    '{{ item }}'
    state:   started
    enabled: yes
  with_items:
    - openstack-nova-api.service
    - openstack-nova-consoleauth.service
    - openstack-nova-scheduler.service
    - openstack-nova-conductor.service
    - openstack-nova-novncproxy.service
