---
- name:         Get list of Compute endpoints.
  register:     openstack_compute_endpoints
  changed_when: no
  command:      openstack endpoint list -f value -c Interface --service compute

- name:    Create Compute endpoints.
  command: 'openstack endpoint create --region {{ region }} compute {{ item.key }} {{ item.value }}'
  when:    '"{{ item.key }}" not in openstack_compute_endpoints.stdout'
  with_dict:
    public:   'http://{{ ip_address }}:8774/v2.1/%(tenant_id)s'
    internal: 'http://{{ ip_address }}:8774/v2.1/%(tenant_id)s'
    admin:    'http://{{ ip_address }}:8774/v2.1/%(tenant_id)s'
