---
- name:         Get list of users.
  register:     openstack_users
  changed_when: no
  command:      openstack user list -f value -c Name --domain default

- name:    Create Nova user.
  command: 'openstack user create --domain default --password {{ keystone_password }} nova'
  when:    '"nova" not in openstack_users.stdout'

- name:         Assign role to Nova user.
  changed_when: no
  command:      'openstack role add --project service --user nova admin'
